[2025-05-06T00:29:26.709+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-06T00:29:26.728+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_snapshot manual__2025-05-06T00:04:35.922172+00:00 [queued]>
[2025-05-06T00:29:26.737+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_snapshot manual__2025-05-06T00:04:35.922172+00:00 [queued]>
[2025-05-06T00:29:26.739+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2025-05-06T00:29:26.753+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2025-05-06 00:04:35.922172+00:00
[2025-05-06T00:29:26.771+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_sequential_run', 'dbt_snapshot', 'manual__2025-05-06T00:04:35.922172+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run_dag.py', '--cfg-path', '/tmp/tmpqxuklf69']
[2025-05-06T00:29:26.773+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3345) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-06T00:29:26.774+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask dbt_snapshot
[2025-05-06T00:29:26.774+0000] {standard_task_runner.py:72} INFO - Started process 3346 to run task
[2025-05-06T00:29:26.802+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_sequential_run.dbt_snapshot manual__2025-05-06T00:04:35.922172+00:00 [running]> on host 5f6a5c55bc08
[2025-05-06T00:29:26.852+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_sequential_run' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T00:04:35.922172+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T00:04:35.922172+00:00'
[2025-05-06T00:29:26.853+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-06T00:29:26.863+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T00:29:26.874+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2025-05-06T00:29:26.891+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T00:29:28.714+0000] {subprocess.py:93} INFO - [0m00:29:28  Running with dbt=1.8.7
[2025-05-06T00:29:29.950+0000] {subprocess.py:93} INFO - [0m00:29:29  Registered adapter: snowflake=1.8.1
[2025-05-06T00:29:31.548+0000] {subprocess.py:93} INFO - [0m00:29:31  Found 12 models, 10 data tests, 7 sources, 459 macros
[2025-05-06T00:29:31.552+0000] {subprocess.py:93} INFO - [0m00:29:31
[2025-05-06T00:29:31.552+0000] {subprocess.py:93} INFO - [0m00:29:31  Nothing to do. Try checking your model configs and model specification args
[2025-05-06T00:29:32.238+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-06T00:29:32.257+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-06T00:29:32.259+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_sequential_run, task_id=dbt_snapshot, run_id=manual__2025-05-06T00:04:35.922172+00:00, execution_date=20250506T000435, start_date=20250506T002926, end_date=20250506T002932
[2025-05-06T00:29:32.286+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-06T00:29:32.305+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T00:29:32.308+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
