[2025-05-05T23:47:01.677+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-05T23:47:01.695+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_run_marts manual__2025-05-05T23:43:53.150272+00:00 [queued]>
[2025-05-05T23:47:01.704+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_run_marts manual__2025-05-05T23:43:53.150272+00:00 [queued]>
[2025-05-05T23:47:01.705+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2025-05-05T23:47:01.719+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run_marts> on 2025-05-05 23:43:53.150272+00:00
[2025-05-05T23:47:01.727+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_sequential_run', 'dbt_run_marts', 'manual__2025-05-05T23:43:53.150272+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run_dag.py', '--cfg-path', '/tmp/tmpked0ix4m']
[2025-05-05T23:47:01.731+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask dbt_run_marts
[2025-05-05T23:47:01.731+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1054) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-05T23:47:01.732+0000] {standard_task_runner.py:72} INFO - Started process 1055 to run task
[2025-05-05T23:47:01.784+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_sequential_run.dbt_run_marts manual__2025-05-05T23:43:53.150272+00:00 [running]> on host 5f6a5c55bc08
[2025-05-05T23:47:01.866+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_sequential_run' AIRFLOW_CTX_TASK_ID='dbt_run_marts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T23:43:53.150272+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T23:43:53.150272+00:00'
[2025-05-05T23:47:01.869+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-05T23:47:01.890+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T23:47:01.892+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt --select marts']
[2025-05-05T23:47:01.901+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T23:47:04.861+0000] {subprocess.py:93} INFO - [0m23:47:04  Running with dbt=1.8.7
[2025-05-05T23:47:06.158+0000] {subprocess.py:93} INFO - [0m23:47:06  Registered adapter: snowflake=1.8.1
[2025-05-05T23:47:08.732+0000] {subprocess.py:93} INFO - [0m23:47:08  Found 12 models, 10 data tests, 7 sources, 459 macros
[2025-05-05T23:47:08.737+0000] {subprocess.py:93} INFO - [0m23:47:08
[2025-05-05T23:47:10.178+0000] {subprocess.py:93} INFO - [0m23:47:10  Concurrency: 4 threads (target='dev')
[2025-05-05T23:47:10.180+0000] {subprocess.py:93} INFO - [0m23:47:10
[2025-05-05T23:47:10.199+0000] {subprocess.py:93} INFO - [0m23:47:10  1 of 5 START sql table model RAW_public.dim_address ............................ [RUN]
[2025-05-05T23:47:10.201+0000] {subprocess.py:93} INFO - [0m23:47:10  2 of 5 START sql table model RAW_public.dim_customer ........................... [RUN]
[2025-05-05T23:47:10.207+0000] {subprocess.py:93} INFO - [0m23:47:10  3 of 5 START sql incremental model RAW_public.fact_churn ....................... [RUN]
[2025-05-05T23:47:13.198+0000] {subprocess.py:93} INFO - [0m23:47:13  3 of 5 OK created sql incremental model RAW_public.fact_churn .................. [[32mSUCCESS 0[0m in 2.98s]
[2025-05-05T23:47:13.203+0000] {subprocess.py:93} INFO - [0m23:47:13  4 of 5 START sql table model RAW_public.churn_metrics .......................... [RUN]
[2025-05-05T23:47:13.812+0000] {subprocess.py:93} INFO - [0m23:47:13  4 of 5 ERROR creating sql table model RAW_public.churn_metrics ................. [[31mERROR[0m in 0.60s]
[2025-05-05T23:47:14.023+0000] {subprocess.py:93} INFO - [0m23:47:14  2 of 5 OK created sql table model RAW_public.dim_customer ...................... [[32mSUCCESS 1[0m in 3.81s]
[2025-05-05T23:47:14.631+0000] {subprocess.py:93} INFO - [0m23:47:14  1 of 5 OK created sql table model RAW_public.dim_address ....................... [[32mSUCCESS 1[0m in 4.42s]
[2025-05-05T23:47:14.636+0000] {subprocess.py:93} INFO - [0m23:47:14  5 of 5 START sql table model RAW_public.churn_map .............................. [RUN]
[2025-05-05T23:47:16.426+0000] {subprocess.py:93} INFO - [0m23:47:16  5 of 5 OK created sql table model RAW_public.churn_map ......................... [[32mSUCCESS 1[0m in 1.78s]
[2025-05-05T23:47:16.448+0000] {subprocess.py:93} INFO - [0m23:47:16
[2025-05-05T23:47:16.448+0000] {subprocess.py:93} INFO - [0m23:47:16  Finished running 1 incremental model, 4 table models in 0 hours 0 minutes and 7.71 seconds (7.71s).
[2025-05-05T23:47:16.571+0000] {subprocess.py:93} INFO - [0m23:47:16
[2025-05-05T23:47:16.572+0000] {subprocess.py:93} INFO - [0m23:47:16  [31mCompleted with 1 error and 0 warnings:[0m
[2025-05-05T23:47:16.573+0000] {subprocess.py:93} INFO - [0m23:47:16
[2025-05-05T23:47:16.574+0000] {subprocess.py:93} INFO - [0m23:47:16    Database Error in model churn_metrics (models/marts/churn_metrics.sql)
[2025-05-05T23:47:16.575+0000] {subprocess.py:93} INFO -   002003 (42S02): SQL compilation error:
[2025-05-05T23:47:16.576+0000] {subprocess.py:93} INFO -   Object 'MONTHLY' does not exist or not authorized.
[2025-05-05T23:47:16.576+0000] {subprocess.py:93} INFO -   compiled code at target/run/customer_churn/models/marts/churn_metrics.sql
[2025-05-05T23:47:16.578+0000] {subprocess.py:93} INFO - [0m23:47:16
[2025-05-05T23:47:16.578+0000] {subprocess.py:93} INFO - [0m23:47:16  Done. PASS=4 WARN=0 ERROR=1 SKIP=0 TOTAL=5
[2025-05-05T23:47:17.282+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-05T23:47:17.303+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-05T23:47:17.347+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-05T23:47:17.369+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-05T23:47:17.373+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
