[2025-05-05T23:45:17.445+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-05T23:45:17.466+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_run_marts scheduled__2025-05-04T02:00:00+00:00 [queued]>
[2025-05-05T23:45:17.478+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_run_marts scheduled__2025-05-04T02:00:00+00:00 [queued]>
[2025-05-05T23:45:17.479+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-05-05T23:45:17.496+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run_marts> on 2025-05-04 02:00:00+00:00
[2025-05-05T23:45:17.506+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_sequential_run', 'dbt_run_marts', 'scheduled__2025-05-04T02:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run_dag.py', '--cfg-path', '/tmp/tmpav0mub6o']
[2025-05-05T23:45:17.511+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask dbt_run_marts
[2025-05-05T23:45:17.511+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=970) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-05T23:45:17.513+0000] {standard_task_runner.py:72} INFO - Started process 971 to run task
[2025-05-05T23:45:17.582+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_sequential_run.dbt_run_marts scheduled__2025-05-04T02:00:00+00:00 [running]> on host 5f6a5c55bc08
[2025-05-05T23:45:17.695+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_sequential_run' AIRFLOW_CTX_TASK_ID='dbt_run_marts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-04T02:00:00+00:00'
[2025-05-05T23:45:17.696+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-05T23:45:17.718+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T23:45:17.720+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt --select marts']
[2025-05-05T23:45:17.730+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T23:45:20.646+0000] {subprocess.py:93} INFO - [0m23:45:20  Running with dbt=1.8.7
[2025-05-05T23:45:21.980+0000] {subprocess.py:93} INFO - [0m23:45:21  Registered adapter: snowflake=1.8.1
[2025-05-05T23:45:23.481+0000] {subprocess.py:93} INFO - [0m23:45:23  Found 12 models, 10 data tests, 7 sources, 459 macros
[2025-05-05T23:45:23.488+0000] {subprocess.py:93} INFO - [0m23:45:23
[2025-05-05T23:45:25.029+0000] {subprocess.py:93} INFO - [0m23:45:25  Concurrency: 4 threads (target='dev')
[2025-05-05T23:45:25.033+0000] {subprocess.py:93} INFO - [0m23:45:25
[2025-05-05T23:45:25.053+0000] {subprocess.py:93} INFO - [0m23:45:25  1 of 5 START sql table model RAW_public.dim_address ............................ [RUN]
[2025-05-05T23:45:25.056+0000] {subprocess.py:93} INFO - [0m23:45:25  2 of 5 START sql table model RAW_public.dim_customer ........................... [RUN]
[2025-05-05T23:45:25.062+0000] {subprocess.py:93} INFO - [0m23:45:25  3 of 5 START sql incremental model RAW_public.fact_churn ....................... [RUN]
[2025-05-05T23:45:28.388+0000] {subprocess.py:93} INFO - [0m23:45:28  2 of 5 OK created sql table model RAW_public.dim_customer ...................... [[32mSUCCESS 1[0m in 3.32s]
[2025-05-05T23:45:28.453+0000] {subprocess.py:93} INFO - [0m23:45:28  3 of 5 OK created sql incremental model RAW_public.fact_churn .................. [[32mSUCCESS 0[0m in 3.38s]
[2025-05-05T23:45:28.463+0000] {subprocess.py:93} INFO - [0m23:45:28  4 of 5 START sql table model RAW_public.churn_metrics .......................... [RUN]
[2025-05-05T23:45:28.600+0000] {subprocess.py:93} INFO - [0m23:45:28  1 of 5 OK created sql table model RAW_public.dim_address ....................... [[32mSUCCESS 1[0m in 3.53s]
[2025-05-05T23:45:28.614+0000] {subprocess.py:93} INFO - [0m23:45:28  5 of 5 START sql table model RAW_public.churn_map .............................. [RUN]
[2025-05-05T23:45:29.205+0000] {subprocess.py:93} INFO - [0m23:45:29  4 of 5 ERROR creating sql table model RAW_public.churn_metrics ................. [[31mERROR[0m in 0.74s]
[2025-05-05T23:45:30.467+0000] {subprocess.py:93} INFO - [0m23:45:30  5 of 5 OK created sql table model RAW_public.churn_map ......................... [[32mSUCCESS 1[0m in 1.83s]
[2025-05-05T23:45:30.488+0000] {subprocess.py:93} INFO - [0m23:45:30
[2025-05-05T23:45:30.490+0000] {subprocess.py:93} INFO - [0m23:45:30  Finished running 4 table models, 1 incremental model in 0 hours 0 minutes and 7.00 seconds (7.00s).
[2025-05-05T23:45:30.675+0000] {subprocess.py:93} INFO - [0m23:45:30
[2025-05-05T23:45:30.677+0000] {subprocess.py:93} INFO - [0m23:45:30  [31mCompleted with 1 error and 0 warnings:[0m
[2025-05-05T23:45:30.680+0000] {subprocess.py:93} INFO - [0m23:45:30
[2025-05-05T23:45:30.684+0000] {subprocess.py:93} INFO - [0m23:45:30    Database Error in model churn_metrics (models/marts/churn_metrics.sql)
[2025-05-05T23:45:30.690+0000] {subprocess.py:93} INFO -   002003 (42S02): SQL compilation error:
[2025-05-05T23:45:30.693+0000] {subprocess.py:93} INFO -   Object 'MONTHLY' does not exist or not authorized.
[2025-05-05T23:45:30.697+0000] {subprocess.py:93} INFO -   compiled code at target/run/customer_churn/models/marts/churn_metrics.sql
[2025-05-05T23:45:30.698+0000] {subprocess.py:93} INFO - [0m23:45:30
[2025-05-05T23:45:30.700+0000] {subprocess.py:93} INFO - [0m23:45:30  Done. PASS=4 WARN=0 ERROR=1 SKIP=0 TOTAL=5
[2025-05-05T23:45:31.345+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-05T23:45:31.360+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-05T23:45:31.367+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_sequential_run, task_id=dbt_run_marts, run_id=scheduled__2025-05-04T02:00:00+00:00, execution_date=20250504T020000, start_date=20250505T234517, end_date=20250505T234531
[2025-05-05T23:45:31.385+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-05T23:45:31.387+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task dbt_run_marts (Bash command failed. The command returned a non-zero exit code 1.; 971)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-05T23:45:31.398+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-05T23:45:31.417+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-05T23:45:31.422+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-05T23:59:37.677+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-05T23:59:37.690+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_run_marts scheduled__2025-05-04T02:00:00+00:00 [queued]>
[2025-05-05T23:59:37.698+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_run_marts scheduled__2025-05-04T02:00:00+00:00 [queued]>
[2025-05-05T23:59:37.699+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-05-05T23:59:37.709+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run_marts> on 2025-05-04 02:00:00+00:00
[2025-05-05T23:59:37.717+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2082) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-05T23:59:37.717+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_sequential_run', 'dbt_run_marts', 'scheduled__2025-05-04T02:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run_dag.py', '--cfg-path', '/tmp/tmp1p1ign0u']
[2025-05-05T23:59:37.719+0000] {standard_task_runner.py:72} INFO - Started process 2083 to run task
[2025-05-05T23:59:37.719+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask dbt_run_marts
[2025-05-05T23:59:37.780+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_sequential_run.dbt_run_marts scheduled__2025-05-04T02:00:00+00:00 [running]> on host 5f6a5c55bc08
[2025-05-05T23:59:37.887+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_sequential_run' AIRFLOW_CTX_TASK_ID='dbt_run_marts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-04T02:00:00+00:00'
[2025-05-05T23:59:37.892+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-05T23:59:37.917+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T23:59:37.919+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt --select marts']
[2025-05-05T23:59:37.932+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T23:59:39.908+0000] {subprocess.py:93} INFO - [0m23:59:39  Running with dbt=1.8.7
[2025-05-05T23:59:41.168+0000] {subprocess.py:93} INFO - [0m23:59:41  Registered adapter: snowflake=1.8.1
[2025-05-05T23:59:42.966+0000] {subprocess.py:93} INFO - [0m23:59:42  Found 12 models, 10 data tests, 7 sources, 459 macros
[2025-05-05T23:59:42.969+0000] {subprocess.py:93} INFO - [0m23:59:42
[2025-05-05T23:59:44.563+0000] {subprocess.py:93} INFO - [0m23:59:44  Concurrency: 4 threads (target='dev')
[2025-05-05T23:59:44.564+0000] {subprocess.py:93} INFO - [0m23:59:44
[2025-05-05T23:59:44.576+0000] {subprocess.py:93} INFO - [0m23:59:44  1 of 5 START sql table model RAW_public.dim_address ............................ [RUN]
[2025-05-05T23:59:44.580+0000] {subprocess.py:93} INFO - [0m23:59:44  2 of 5 START sql table model RAW_public.dim_customer ........................... [RUN]
[2025-05-05T23:59:44.583+0000] {subprocess.py:93} INFO - [0m23:59:44  3 of 5 START sql incremental model RAW_public.fact_churn ....................... [RUN]
[2025-05-05T23:59:47.248+0000] {subprocess.py:93} INFO - [0m23:59:47  3 of 5 OK created sql incremental model RAW_public.fact_churn .................. [[32mSUCCESS 0[0m in 2.65s]
[2025-05-05T23:59:47.256+0000] {subprocess.py:93} INFO - [0m23:59:47  4 of 5 START sql table model RAW_public.churn_metrics .......................... [RUN]
[2025-05-05T23:59:48.080+0000] {subprocess.py:93} INFO - [0m23:59:48  2 of 5 OK created sql table model RAW_public.dim_customer ...................... [[32mSUCCESS 1[0m in 3.49s]
[2025-05-05T23:59:48.144+0000] {subprocess.py:93} INFO - [0m23:59:48  1 of 5 OK created sql table model RAW_public.dim_address ....................... [[32mSUCCESS 1[0m in 3.56s]
[2025-05-05T23:59:48.150+0000] {subprocess.py:93} INFO - [0m23:59:48  5 of 5 START sql table model RAW_public.churn_map .............................. [RUN]
[2025-05-05T23:59:49.304+0000] {subprocess.py:93} INFO - [0m23:59:49  4 of 5 OK created sql table model RAW_public.churn_metrics ..................... [[32mSUCCESS 1[0m in 2.04s]
[2025-05-05T23:59:50.439+0000] {subprocess.py:93} INFO - [0m23:59:50  5 of 5 OK created sql table model RAW_public.churn_map ......................... [[32mSUCCESS 1[0m in 2.28s]
[2025-05-05T23:59:50.458+0000] {subprocess.py:93} INFO - [0m23:59:50
[2025-05-05T23:59:50.460+0000] {subprocess.py:93} INFO - [0m23:59:50  Finished running 1 incremental model, 4 table models in 0 hours 0 minutes and 7.49 seconds (7.49s).
[2025-05-05T23:59:50.707+0000] {subprocess.py:93} INFO - [0m23:59:50
[2025-05-05T23:59:50.708+0000] {subprocess.py:93} INFO - [0m23:59:50  [32mCompleted successfully[0m
[2025-05-05T23:59:50.709+0000] {subprocess.py:93} INFO - [0m23:59:50
[2025-05-05T23:59:50.711+0000] {subprocess.py:93} INFO - [0m23:59:50  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 TOTAL=5
[2025-05-05T23:59:51.373+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-05T23:59:51.400+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-05T23:59:51.401+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_sequential_run, task_id=dbt_run_marts, run_id=scheduled__2025-05-04T02:00:00+00:00, execution_date=20250504T020000, start_date=20250505T235937, end_date=20250505T235951
[2025-05-05T23:59:51.439+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-05T23:59:51.471+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-05T23:59:51.478+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
