[2025-05-06T00:00:00.237+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-06T00:00:00.252+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_snapshot scheduled__2025-05-04T02:00:00+00:00 [queued]>
[2025-05-06T00:00:00.260+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_snapshot scheduled__2025-05-04T02:00:00+00:00 [queued]>
[2025-05-06T00:00:00.261+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-06T00:00:00.271+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2025-05-04 02:00:00+00:00
[2025-05-06T00:00:00.277+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2269) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-06T00:00:00.277+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_sequential_run', 'dbt_snapshot', 'scheduled__2025-05-04T02:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run_dag.py', '--cfg-path', '/tmp/tmps4olvmr6']
[2025-05-06T00:00:00.279+0000] {standard_task_runner.py:72} INFO - Started process 2270 to run task
[2025-05-06T00:00:00.280+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask dbt_snapshot
[2025-05-06T00:00:00.319+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_sequential_run.dbt_snapshot scheduled__2025-05-04T02:00:00+00:00 [running]> on host 5f6a5c55bc08
[2025-05-06T00:00:00.372+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_sequential_run' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-04T02:00:00+00:00'
[2025-05-06T00:00:00.373+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-06T00:00:00.383+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T00:00:00.384+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2025-05-06T00:00:00.390+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T00:00:01.612+0000] {subprocess.py:93} INFO - [0m00:00:01  Running with dbt=1.8.7
[2025-05-06T00:00:02.279+0000] {subprocess.py:93} INFO - [0m00:00:02  Registered adapter: snowflake=1.8.1
[2025-05-06T00:00:03.656+0000] {subprocess.py:93} INFO - [0m00:00:03  Found 12 models, 10 data tests, 7 sources, 459 macros
[2025-05-06T00:00:03.660+0000] {subprocess.py:93} INFO - [0m00:00:03
[2025-05-06T00:00:03.661+0000] {subprocess.py:93} INFO - [0m00:00:03  Nothing to do. Try checking your model configs and model specification args
[2025-05-06T00:00:04.650+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-06T00:00:04.669+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-06T00:00:04.669+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_sequential_run, task_id=dbt_snapshot, run_id=scheduled__2025-05-04T02:00:00+00:00, execution_date=20250504T020000, start_date=20250506T000000, end_date=20250506T000004
[2025-05-06T00:00:04.703+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-06T00:00:04.726+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T00:00:04.730+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
