[2025-05-05T23:59:51.990+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-05T23:59:52.012+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_snapshot manual__2025-05-05T23:53:52.064784+00:00 [queued]>
[2025-05-05T23:59:52.024+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_snapshot manual__2025-05-05T23:53:52.064784+00:00 [queued]>
[2025-05-05T23:59:52.025+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-05T23:59:52.044+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2025-05-05 23:53:52.064784+00:00
[2025-05-05T23:59:52.055+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2186) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-05T23:59:52.053+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_sequential_run', 'dbt_snapshot', 'manual__2025-05-05T23:53:52.064784+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run_dag.py', '--cfg-path', '/tmp/tmpgo6gxhaw']
[2025-05-05T23:59:52.056+0000] {standard_task_runner.py:72} INFO - Started process 2187 to run task
[2025-05-05T23:59:52.057+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask dbt_snapshot
[2025-05-05T23:59:52.113+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_sequential_run.dbt_snapshot manual__2025-05-05T23:53:52.064784+00:00 [running]> on host 5f6a5c55bc08
[2025-05-05T23:59:52.218+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_sequential_run' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T23:53:52.064784+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T23:53:52.064784+00:00'
[2025-05-05T23:59:52.222+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-05T23:59:52.250+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T23:59:52.253+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2025-05-05T23:59:52.265+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T23:59:53.664+0000] {subprocess.py:93} INFO - [0m23:59:53  Running with dbt=1.8.7
[2025-05-05T23:59:54.509+0000] {subprocess.py:93} INFO - [0m23:59:54  Registered adapter: snowflake=1.8.1
[2025-05-05T23:59:55.650+0000] {subprocess.py:93} INFO - [0m23:59:55  Found 12 models, 10 data tests, 7 sources, 459 macros
[2025-05-05T23:59:55.654+0000] {subprocess.py:93} INFO - [0m23:59:55
[2025-05-05T23:59:55.655+0000] {subprocess.py:93} INFO - [0m23:59:55  Nothing to do. Try checking your model configs and model specification args
[2025-05-05T23:59:56.594+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-05T23:59:56.629+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-05T23:59:56.631+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_sequential_run, task_id=dbt_snapshot, run_id=manual__2025-05-05T23:53:52.064784+00:00, execution_date=20250505T235352, start_date=20250505T235952, end_date=20250505T235956
[2025-05-05T23:59:56.687+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-05T23:59:56.704+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
